[workspace.package]
license = "MIT-0"
authors = ["Parity Technologies <admin@parity.io>"]
homepage = "https://paritytech.github.io/polkadot-sdk/"
repository = "https://github.com/paritytech/polkadot-sdk-minimal-template.git"
edition = "2021"

[workspace]
default-members = ["pallets/airdrop", "runtime"]
members = [
    "node",
    "pallets/airdrop",
    "runtime",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.13" }
codec = { version = "3.7.4", default-features = false, package = "parity-scale-codec" }
docify = { version = "0.2.9" }
frame-benchmarking = { version = "38.0.0", default-features = false }
frame-benchmarking-cli = "43.0.0"
futures = { version = "0.3.31" }
futures-timer = { version = "3.0.2" }
jsonrpsee = { version = "0.24.3" }
airdrop-runtime = { path = "./runtime", default-features = false }
pallet-airdrop = { path = "./pallets/airdrop", default-features = false }
polkadot-primitives = { version = "19.0.0", default-features = false }
polkadot-sdk = { version = "2506.0.0", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
scale-info = { version = "2.11.6", default-features = false }
serde = { version = "1.0.214", default-features = false }
serde_json = { version = "1.0.132", default-features = false }

[profile.release]
opt-level = 3
panic = "unwind"

[profile.production]
codegen-units = 1
inherits = "release"
lto = true
